[web] Fix 'npm run build' tsc errors
src/App.test.tsx:4:1 - error TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

src/App.test.tsx:7:3 - error TS2304: Cannot find name 'expect'.

src/misc/utils.ts:2:31 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.