.github/workflows/web.yml fix
I'm getting the error TypeError: crypto.getRandomValues is not a function.
It's due to using node 16, see:
https://github.com/vuejs/vitepress/issues/3090
https://github.com/vitejs/vite/issues/19407

Also change 'npm run eslint' to 'npm run lint' required after the Vite migration.