[server] Fix 'npm test' requiring ts-node
When running 'npm test' it fails with this error:

Error: Jest: Failed to parse the TypeScript config file /Users/albert/Programming/Node/Projects/RecipeManager/server/jest.config.ts
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find package 'ts-node' imported from /Users/albert/Programming/Node/Projects/RecipeManager/server/node_modules/jest-config/build/readConfigFileAndSetRootDir.js

Jest requires ts-node for TypeScript configuration files (jest.config.ts), see
https://jestjs.io/docs/configuration

I've opted to rename jest.config.ts to jest.config.js to avoid installing ts-node, which BTW is
unmaintained (last commit is from 2023).

The // eslint-disable-next-line import/no-default-export comment is no longer needed since this is
module.exports now (CommonJS).